# Generated by Django 6.0.1 on 2026-04-12 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('system', 'System'), ('achievement', 'Achievement')], default='system', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('avatar_text', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(default='#6366F1', max_length=10)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
