# Generated by Django 6.0.1 on 2026-04-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='oauth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'GitHub'), ('google', 'Google')], default='email', max_length=20),
        ),
    ]
